/*******************************************************/
// P5.play: formula racing game
// racing car game
// Written by Tom
// The file "bahraintrackworking.png" is generated by ChatGPT
// The file "ferrari.png" and "finishline.png" were created by me
// The file "f1caricon.png" is from https://hum2d.com/free/f1-racing-car/ 
/*******************************************************/

/*******************************************************/
// setup()
/*******************************************************/
function preload() {

  //Load images

  imgCar = loadImage('assets/images/ferrari.png');

  imgTrack = loadImage('assets/images/bahraintrackworking.png');

  imgLine = loadImage('assets/images/Finshline.png');

}
//Variables
let width = 800;
let height = 800;
let timer = 0;


function setup() {
  console.log("setup: ");

  cnv = new Canvas(windowWidth - 50, windowHeight - 50);

frameRate(60);



  /***********************************************************/
  //Create new sprites
  /***********************************************************/

  track = new Sprite(width / 2, height / 2, 3200, 1800, 'n');
  track.image = (imgTrack)
  track.scale = 10000 / imgTrack.width;
  track.debug = true;

  finishLine = new Sprite(width / 2, 2105, 50, 50, 'n');
  finishLine.image = (imgLine);
  finishLine.scale = 4;

  car = new Sprite(width / 2, height / 2, 50, 50);
  car.image = (imgCar);
  car.scale = 0.75;
  car.rotation = 90;
  car.maxSpeed = 20;
  car.speed = 0;
  car.debug = true;
  
  timerBar = new Sprite(camera.x, camera.y, 300,300,'n');









  //wallLH = new Sprite(0, imgTrack.height / 2, 8, imgTrack.height, 'k');

  //wallRH = new Sprite(imgTrack.width, imgTrack.height / 2, 8, imgTrack.width, 'k');

  //wallTop = new Sprite(imgTrack.width / 2, 0, imgTrack.width, 30, 'k');

  //wallBot = new Sprite(imgTrack.width / 2, imgTrack.height, imgTrack.width, 30, 'k');

  //wallLH.color = 'black';
  //wallRH.color = 'black';
  //wallTop.color = 'black';
  //wallBot.color = 'black';


}

/*******************************************************/
// draw()
/*******************************************************/
function draw() {
  background('darkgreen');
  camera.x = car.x;
  camera.y = car.y;
  camera.zoom = 0.5;




  //******************************************************/
  //Keyboard Movements//
  //******************************************************/
  if (kb.pressing('a')) {

    car.rotation = car.rotation - 2;
    car.direction = car.rotation;
  }

  if (kb.pressing('d')) {
    car.rotation = car.rotation + 2;
    car.direction = car.rotation;

  }


  if (kb.pressing('w')) {

    if (car.speed < 20) {
      car.speed += 0.3;
    }

    car.direction = car.rotation;
  }



  if (kb.pressing('s')) {
    car.speed -= 0.3;
    car.direction = car.rotation;
  }
//******************************************************/	
  console.log(car.speed);
  // Dust code for when the sprite drives off the track

  if (track.overlaps(car) !== false) {
    console.log("this working");
    for (i = 0; i < 10; i++) {
      dust = new Sprite(car.x, car.y, 5, 5, 'n');
      dust.speed = 8;
      dust.color = "darkgreen";
      dust.direction = random(car.direction - 30, car.direction + 30);
    }
  }
timer = frameCount/60;

timer = Math.round(timer*100)/100;

 

timerBar.moveTowards(camera.x-(width+1000),camera.y-(height+20),1);
timerBar.text = timer;
timerBar.textSize = 40;




}
